import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";
import { AppProvider } from "@/providers";
import { QueryClient } from "@tanstack/react-query";
import { fetchRoles } from "@/hooks/queries/use-role.query";
import i18nConfig from '@/i18nConfig';
import { dir } from 'i18next';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }));
}
export default function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const queryClient = new QueryClient();
  queryClient.prefetchQuery({
    queryKey: ["roles"],
    queryFn: () => fetchRoles,
  });
  return (
    <html lang={locale} dir={dir(locale)}>
      <body className={inter.className}>
        {/* <div className="w-full min-h-screen bg-gray-100"> */}
          {/* {children} */}
        {/* </div> */}
        <AppProvider>
          {/* <UIControllerProvider> */}
          {children}
          {/* </UIControllerProvider> */}
        </AppProvider>
      </body>
    </html>
  );
}
